Management/Models/Annotations/Panel.cs
using DisplayMonkey.Language;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DisplayMonkey.Models
{
    [
        MetadataType(typeof(Panel.Annotations))
    ]
    public partial class Panel
    {
        public Panel(DisplayMonkeyEntities _db)
        {
            init(_db);
        }
        
        protected virtual void init(DisplayMonkeyEntities _db)
        {
            Setting fadeLength = Setting.GetSetting(_db, Setting.Keys.DefaultPanelFadeLength);
            if (fadeLength != null)
            {
                this.FadeLength = fadeLength.DecimalValue;
            }
        }
        
        internal class Annotations
        {
            [
                Display(ResourceType = typeof(Resources), Name = "ID"),
                Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IDRequired"),
            ]
            public int PanelId { get; set; }

            [Display(ResourceType = typeof(Resources), Name = "Canvas"),
             Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "CanvasRequired"),
         ]
            public int CanvasId { get; set; }

            [
                Display(ResourceType = typeof(Resources), Name = "Top"),
                Required(ErrorMessageResourceType = typeof(Resources),
                    ErrorMessageResourceName = "PositiveIntegerRequired"),
                Range(0, Int32.MaxValue,
                    ErrorMessageResourceType = typeof(Resources),
                    ErrorMessageResourceName = "PositiveIntegerRequired"),

            ]
            public int Top { get; set; }

            [
                Display(ResourceType = typeof(Resources), Name = "Left"),
                Required(ErrorMessageResourceType = typeof(Resources),
                    ErrorMessageResourceName = "PositiveIntegerRequired"),
                Range(0, Int32.MaxValue,
                    ErrorMessageResourceType = typeof(Resources),
                    ErrorMessageResourceName = "PositiveIntegerRequired"),
            ]
            public int Left { get; set; }

            [
                Display(ResourceType = typeof(Resources), Name = "Height"),
                Required(ErrorMessageResourceType = typeof(Resources),
                    ErrorMessageResourceName = "PositiveIntegerRequired"),
                Range(1, Int32.MaxValue,
                    ErrorMessageResourceType = typeof(Resources),
                    ErrorMessageResourceName = "PositiveIntegerRequired"),
            ]
            public int Height { get; set; }

            [
                Display(ResourceType = typeof(Resources), Name = "Width"),
                Required(ErrorMessageResourceType = typeof(Resources),
                    ErrorMessageResourceName = "PositiveIntegerRequired"),
                Range(1, Int32.MaxValue,
                    ErrorMessageResourceType = typeof(Resources),
                    ErrorMessageResourceName = "PositiveIntegerRequired"),
            ]
            public int Width { get; set; }

            [
                Display(ResourceType = typeof(Resources), Name = "Name"),
                Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "NameRequired"),
                StringLength(100, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "MaxLengthExceeded"),
            ]
            public string Name { get; set; }

            [
                Display(ResourceType = typeof(Resources), Name = "FadeLength"),
                Range(0, Int32.MaxValue,
                    ErrorMessageResourceType = typeof(Resources),
                    ErrorMessageResourceName = "PositiveIntegerRequired"),
            ]
            public double FadeLength { get; set; }

            [
                Display(ResourceType = typeof(Resources), Name = "Canvas"),
            ]
            public virtual Canvas Canvas { get; set; }

            [
                Display(ResourceType = typeof(Resources), Name = "Frames"),
            ]
            public virtual ICollection<Frame> Frames { get; set; }

            /*[
                Display(ResourceType = typeof(Resources), Name = "FullScreens"),
            ]
            public virtual ICollection<FullScreen> FullScreens { get; set; }*/
        }

        [
            NotMapped,
        ]
        public bool IsFullscreen
        {
            get
            {
                return this is FullScreen;
            }
        }
    }
}

Management/Models/Panel.cs
/*!
* DisplayMonkey source file
* http://displaymonkey.org
*
* Copyright (c) 2019 Fuel9 LLC and contributors
*
* Released under the MIT license:
* http://opensource.org/licenses/MIT
*/

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayMonkey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panel
    {
        public Panel()
        {
            this.Frames = new HashSet<Frame>();
        }
    
        public int PanelId { get; set; }
        public int CanvasId { get; set; }
        public int Top { get; set; }
        public int Left { get; set; }
        public int Height { get; set; }
        public int Width { get; set; }
        public string Name { get; set; }
        public byte[] Version { get; set; }
        public double FadeLength { get; set; }
    
        public virtual Canvas Canvas { get; set; }
        public virtual ICollection<Frame> Frames { get; set; }
    }
}

Management/Controllers/PanelController.cs
/*!
* DisplayMonkey source file
* http://displaymonkey.org
*
* Copyright (c) 2015 Fuel9 LLC and contributors
*
* Released under the MIT license:
* http://opensource.org/licenses/MIT
*/

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DisplayMonkey.Models;

using System.Web.Script.Serialization;

namespace DisplayMonkey.Controllers
{
    public class PanelController : BaseController
    {
        private DisplayMonkeyEntities db = new DisplayMonkeyEntities();

        private void FillCanvasSelectList(object selected = null)
        {
            var list = db.Canvases
                .OrderBy(c => c.Name)
                .ToList()
                ;

            ViewBag.Canvases = new SelectList(list, "CanvasId", "Name", selected);
        }


        //
        // GET: /Panel/

        public ActionResult Index(int canvasId = 0, string name = "")
        {
            IQueryable<Panel> list = db.Panels
                .OrderBy(p => p.Canvas.Name)
                .ThenBy(p => p.Name)
                ;

            if (!String.IsNullOrEmpty(name) || canvasId > 0)
            {
                list = list
                    .Where(s => (
                        (canvasId == 0 || s.CanvasId == canvasId) &&
                        (String.IsNullOrEmpty(name) || s.Name.Contains(name))
                    )
                );
            }

            FillCanvasSelectList(canvasId);

            return View(list.ToList());
        }

        //
        // GET: /Panel/Details/5

        public ActionResult Details(int id = 0)
        {
            Panel panel = db.Panels.Find(id);
            if (panel == null)
            {
                return View("Missing", new MissingItem(id));
            }

            panel.Frames = db.Frames
                .Where(f => f.PanelId == panel.PanelId)
                .OrderBy(f => f.Sort == null ? (float)f.FrameId : (float)f.Sort)
                .ThenBy(f => f.FrameId)
                .ToList()
                ;

            return View(panel);
        }

        //
        // GET: /Panel/Create

        public ActionResult Create(int canvasId = 0)
        {
            Panel panel = new Panel(db);

            FillCanvasSelectList(canvasId);

            return View(panel);
        }

        //
        // POST: /Panel/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Panel panel)
        {
            if (ModelState.IsValid)
            {
                db.Panels.Add(panel);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            FillCanvasSelectList(panel.CanvasId);
            
            return View(panel);
        }

        //
        // GET: /Panel/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Panel panel = db.Panels.Find(id);
            if (panel == null)
            {
                return View("Missing", new MissingItem(id));
            }

            return View(panel);
        }

        //
        // POST: /Panel/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Panel panel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(panel).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(panel);
        }

        //
        // GET: /Panel/EditFS/5

        public ActionResult EditFS(int id = 0)
        {
            FullScreen fs = db.Panels
                .OfType<FullScreen>()
                //.Find(id)
                //.FullScreens
                .FirstOrDefault(f => f.PanelId == id)
                ;

            if (fs == null)
            {
                return View("Missing", new MissingItem(id));
            }

            //fs.FadeLength = fs.Panel.FadeLength;

            return View(fs);
        }

        //
        // POST: /Panel/EditFS/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditFS(FullScreen fs)
        {
            if (ModelState.IsValid)
            {
                Panel panel = db.Panels.Find(fs.PanelId);
                panel.FadeLength = fs.FadeLength;
                db.Entry(panel).State = EntityState.Modified;
                //db.Entry(fs).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            
            return View(fs);
        }

        //
        // GET: /Panel/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Panel panel = db.Panels.Find(id);
            if (panel == null)
            {
                return View("Missing", new MissingItem(id));
            }

            return View(panel);
        }

        //
        // POST: /Panel/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Panel panel = db.Panels.Find(id);

            if (!panel.IsFullscreen)
            {
                db.Panels.Remove(panel);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        //
        // GET: /Panel/SortFrames/5

        public ActionResult SortFrames(int id = 0)
        {
            var list = db.Frames
                .Where(f => f.PanelId == id)
                .Include(f => f.Panel.Canvas)
                .AsEnumerable()             // sort in controller
                .OrderBy(f => f.Sort == null ? (float)f.FrameId : (float)f.Sort)
                .ThenBy(f => f.FrameId)
                ;

            return View(list.ToList());
        }

        //
        // POST: /Panel/Delete/5

        private class SortedId
        {
            public int newSort { get; set; }
            public int oldSort { get; set; }
            public int frameId { get; set; }
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SortFrames(int panelId, string json)
        {
            JavaScriptSerializer ser = new JavaScriptSerializer();
            var sortedIds = ser.Deserialize<List<SortedId>>(json);
            int prevFrameId = 0; sortedIds.ForEach(s =>
            {
                Frame frame = db.Frames.Find(s.frameId);
                frame.Sort = s.newSort;
                db.Entry(frame).Property(f => f.Sort).IsModified = true;
                prevFrameId = s.frameId;
            });
            db.SaveChanges();
            return RedirectToAction("Details", new { id = panelId });
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Management/Views/Panel/Create.cshtml
@model DisplayMonkey.Models.Panel

@{
    ViewBag.Title = Resources.CreateNewPanel;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.Referrer()

    <fieldset>
        <legend>@Resources.Panel</legend>
        <table><tr>
        <td>

        <div class="editor-label">
            @Html.LabelFor(model => model.Canvas)
        </div>
        <div class="editor-field select">
            @Html.DropDownList("CanvasId", ViewBag.Canvases as SelectList)
            @Html.ValidationMessageFor(model => model.CanvasId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Top)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Top, new { htmlAttributes = new { @class = "pixels" }, }) @Resources.Pixels
            @Html.ValidationMessageFor(model => model.Top)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Left)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Left, new { htmlAttributes = new { @class = "pixels" }, }) @Resources.Pixels
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Width)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Width, new { htmlAttributes = new { @class = "pixels" }, }) @Resources.Pixels
            @Html.ValidationMessageFor(model => model.Width)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Height)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "pixels" }, }) @Resources.Pixels
            @Html.ValidationMessageFor(model => model.Height)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FadeLength)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FadeLength, new { htmlAttributes = new { @class = "duration" } }) @Resources.Sec
            @Html.ValidationMessageFor(model => model.FadeLength)
        </div>

        <p>
            <input type="submit" value="@Resources.Create" />
        </p>
        </td>
        <td class="preview">
            <div id="canvas" data-path="@Html.Raw(Url.Action("Data", "Canvas"))">
                <div>
                    <img src="@Html.Raw(Url.Action("Thumb", "Media", new { id="nnn", width="qqq", height="qqq" }))" alt="Background" />
                </div>
            </div>
        </td>
    </tr></table>
    </fieldset>
}

<div>
    @Html.ActionLink(Resources.ViewPanels, "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jsquery")
    @Scripts.Render("~/bundles/panel")
}

Management/Views/Panel/Delete.cshtml
@model DisplayMonkey.Models.Panel

@{
    ViewBag.Title = Resources.DeletePanel;
}

<h2>@ViewBag.Title</h2>

<h3>@Resources.AreYouSureYouWantToDeleteThisPanel</h3>

@Html.Partial("_Details")

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.Referrer()
    <p>
        <input type="submit" value="@Resources.Delete" /> |
        @Html.ActionLink(Resources.ViewPanels, "Index")
    </p>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jsquery")
    @Scripts.Render("~/bundles/panel")
}

Management/Views/Panel/Details.cshtml
@model DisplayMonkey.Models.Panel

@{
    ViewBag.Title = Resources.PanelDetails;
}

<h2>@ViewBag.Title</h2>

@Html.Partial("_Details")

<p>
    @if (Model.IsFullscreen)
    {
        @Html.ActionLink(Resources.Edit, "EditFS", new { id=Model.PanelId })
    }
    else
    {
        @Html.ActionLink(Resources.Edit, "Edit", new { id=Model.PanelId })
    }
     | @Html.ActionLink(Resources.ViewPanels, "Index")
</p>

<h2>@Resources.AssociatedFrames</h2>

@Html.ActionLink(Resources.CreateNewFrame, "Create", "Frame", new { PanelId = Model.PanelId }, null)
@if (Model.Frames.Count > 1) 
{ 
    @(" | ")@Html.ActionLink(Resources.ReOrderFrames, "SortFrames", new { id = Model.PanelId })
}

@Html.Partial("_frameList", Model.Frames)

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jsquery")
    @Scripts.Render("~/bundles/panel")
}

Management/Views/Panel/Edit.cshtml
@model DisplayMonkey.Models.Panel

@{
    ViewBag.Title = Resources.EditPanel;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.Referrer()

    <fieldset>
        <legend>@Resources.Panel</legend>
        <table><tr>
        <td>

        @Html.HiddenFor(model => model.PanelId)
        @Html.HiddenFor(model => model.CanvasId)

        <div class="editor-label">
            @Html.LabelFor(model => model.Canvas)
        </div>
        <div class="editor-field">
            @Html.DisplayFor(model => model.Canvas.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Top)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Top, new { htmlAttributes = new { @class = "pixels" }, }) @Resources.Pixels
            @Html.ValidationMessageFor(model => model.Top)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Left)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Left, new { htmlAttributes = new { @class = "pixels" }, })  @Resources.Pixels
            @Html.ValidationMessageFor(model => model.Left)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Width)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Width, new { htmlAttributes = new { @class = "pixels" }, }) @Resources.Pixels
            @Html.ValidationMessageFor(model => model.Width)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Height)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "pixels" }, })  @Resources.Pixels
            @Html.ValidationMessageFor(model => model.Height)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FadeLength)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FadeLength, new { htmlAttributes = new { @class = "duration" } }) @Resources.Sec
            @Html.ValidationMessageFor(model => model.FadeLength)
        </div>

        <p>
            <input type="submit" value="@Resources.Save" />
        </p>
        </td>
        <td class="preview">
            <div id="canvas" data-path="@Html.Raw(Url.Action("Data", "Canvas"))">
                <div>
                    <img src="@Html.Raw(Url.Action("Thumb", "Media", new { id="nnn", width="qqq", height="qqq" }))" alt="Background" />
                </div>
            </div>
        </td>
    </tr></table>
    </fieldset>
}

<div>
    @Html.ActionLink(Resources.ViewPanels, "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jsquery")
    @Scripts.Render("~/bundles/panel")
}

Management/Views/Panel/EditFS.cshtml
@model DisplayMonkey.Models.FullScreen

@{
    ViewBag.Title = Resources.EditFullScreenPanel;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.Referrer()

    <fieldset>
        <legend>@Resources.Panel</legend>

        @Html.HiddenFor(model => model.PanelId)

        <div class="editor-label">
            @Html.LabelFor(model => model.Canvas)
        </div>
        <div class="editor-field">
            @Html.HiddenFor(model => model.CanvasId)
            @Html.DisplayFor(model => model.Canvas.Name), @Html.DisplayFor(model => model.Canvas.Width) x @Html.DisplayFor(model => model.Canvas.Height) @Resources.Pixels
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MaxIdleInterval)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MaxIdleInterval, new { htmlAttributes = new { @class = "duration" } }) @Resources.Sec
            @Html.ValidationMessageFor(model => model.MaxIdleInterval)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FadeLength)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FadeLength, new { htmlAttributes = new { @class = "duration" } }) @Resources.Sec
            @Html.ValidationMessageFor(model => model.FadeLength)
        </div>

        <p>
            <input type="submit" value="@Resources.Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink(Resources.ViewPanels, "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Management/Views/Panel/Index.cshtml
@model IEnumerable<DisplayMonkey.Models.Panel>

@{
    ViewBag.Title = Resources.Panels;
    const string sep = "| ";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Index", "Panel", FormMethod.Get))
{    
    <fieldset><legend>@Resources.Search</legend><table>
        <tr><td>@Resources.Canvas:</td><td><div class="select">@Html.DropDownList("CanvasId", ViewBag.Canvases as SelectList, Resources.Any)</div></td></tr>
        <tr><td>@Resources.Name:</td><td>@Html.TextBox("name")</td></tr>
    <tr><td colspan="2"><input type="submit" value="@Resources.Filter" /></td></tr></table></fieldset> 
}

<p>
    @Html.ActionLink(Resources.CreateNewPanel, "Create", new { canvasId = ViewBag.Canvases.SelectedValue })
</p>
<table class="grid">
    <tr>
        <th>
        </th>
        <th class="nw">
            @Resources.Canvas
        </th>
        <th>
            @Resources.Panel
        </th>
        <th class="nw">
            @Resources.Options
        </th>
        <th class="nw"></th>
    </tr>

@foreach (var item in Model)
{
    FullScreen fs = item.Canvas.FullScreen;
    
    <tr>
        <td>
            @if (fs.PanelId == item.PanelId)
            {
                <img alt="Fullscreen" src="images/full.png" />
            }
            else
            {
                <img alt="Fullscreen" src="images/partial.png" />
            }
        </td>
        <td class="nw">
            @Html.DisplayFor(modelItem => item.Canvas.Name)
        </td>
        <td>
            @Html.ActionLink(item.Name, "Details", "Panel", new { id=item.PanelId }, null)
        </td>
        <td class="nw">
            @if (fs.PanelId == item.PanelId)
            {
                @Html.DisplayNameFor(m => m.Canvas.FullScreen.MaxIdleInterval)
                if (fs.MaxIdleInterval == null) 
                {
                    @(": ")@Resources.NotSet
                }
                else
                {
                    @(": ")@fs.MaxIdleInterval@(" ")@Resources.Sec
                }
            }
            else
            {
                @(string.Format(Resources.PositionSize, 
                    item.Top, 
                    item.Left, 
                    item.Width,
                    item.Height))
            }
        </td>
        <td class="nw">
            @if (fs.PanelId != item.PanelId)
            {
                @Html.ActionLink(Resources.Edit, "Edit", "Panel", new { id=item.PanelId }, null)
            }
            else
            {
                @Html.ActionLink(Resources.Edit, "EditFS", "Panel", new { id=item.PanelId }, null)
            }
            @if (fs.PanelId != item.PanelId)
            {
                @sep @Html.ActionLink(Resources.Delete, "Delete", "Panel", new { id=item.PanelId }, null)
            }
        </td>
    </tr>
}

</table>

Management/Views/Panel/SortFrames.cshtml
@model IEnumerable<DisplayMonkey.Models.Frame>

@{
    ViewBag.Title = Resources.ReOrderPanelFrames;
    string frameContent = "";
    int i = 0;
}

<h2>@ViewBag.Title</h2>

<ul id="film">

@foreach (var item in Model)
{
    <li data-frame-id="@item.FrameId" data-old-sort="@((i++).ToString())">
        @{frameContent = item.FrameType + ": ";}

        @if (item is Clock)
        {
            @Html.Partial("../Clock/_Film", item)
        }
        else if (item is Html)
        {
            @Html.Partial("../Html/_Film", item)
        }
        else if (item is Memo)
        {
            @Html.Partial("../Memo/_Film", item)
        }
        else if (item is Outlook)
        {
            @Html.Partial("../Outlook/_Film", item)
        }
        else if (item is Picture)
        {
            @Html.Partial("../Picture/_Film", item)
        }
        else if (item is Powerbi)
        {
            @Html.Partial("../Powerbi/_Film", item)
        }
        else if (item is Report)
        {
            @Html.Partial("../Report/_Film", item)
        }
        else if (item is Video)
        {
            @Html.Partial("../Video/_Film", item)
        }
        else if (item is Weather)
        {
            @Html.Partial("../Weather/_Film", item)
        }
        else if (item is Youtube)
        {
            @Html.Partial("../Youtube/_Film", item)
        }
        else
        {
            <div class="d1">
                <div><img src="~/images/unknown.png" alt="" /></div>
                <div>@(string.Format("{0}, {1} {2}", item.FrameType, item.Duration, Resources.Sec))</div>
            </div>
            <div></div>
        }

    </li>
}

</ul>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.Referrer()
    
    @Html.HiddenFor(m => Model.FirstOrDefault().PanelId)
    @Html.Hidden("json")
    <p>
        <input id="submit" type="submit" value="@Resources.Save" /> |
        <a href="javascript:window.history.back();">@Resources.BackPreviousPage</a>
    </p>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jsquery")
    <script type="text/javascript">
        $(document).ready(function() {
            $('#film')
                .sortable()
                .disableSelection()
            ;

            $('#submit').click(function (event) {
                var json = [];
                $('#film li').each(function (i, e) {
                    json.push({
                        'newSort': i,
                        'oldSort': $(e).data('old-sort'),
                        'frameId': $(e).data('frame-id')
                    });
                });
                $('#json').val(JSON.stringify(json));
            });
        });
    </script>
}

Management/Views/Panel/_Details.cshtml
@model DisplayMonkey.Models.Panel

@{
    FullScreen fs = Model.Canvas.FullScreen;
}

<fieldset>
    <legend>@Resources.Panel</legend>
        <table><tr>
        <td>

    @Html.HiddenFor(p => p.CanvasId)
    @Html.HiddenFor(p => p.PanelId)
    @Html.HiddenFor(p => p.Top)
    @Html.HiddenFor(p => p.Left)
    @Html.HiddenFor(p => p.Width)
    @Html.HiddenFor(p => p.Height)

    <div class="divTable">
    <div class="divRow">
    <div class="display-label">
        @Resources.Canvas
    </div>
    <div class="display-field">
        @Html.ActionLink(Model.Canvas.Name, "Details", "Canvas", new { id=Model.CanvasId }, null)
    </div>
    </div>

    <div class="divRow">
    <div class="display-label">
        @Resources.Panel
    </div>
    <div class="display-field">
        @Html.Label(Model.Name)
        @if (fs.PanelId == Model.PanelId)
        {
            int m = fs.MaxIdleInterval ?? -1;
            string maxInterval = m < 0 ? Resources.Auto : m.ToString();
            
            @(string.Format(Resources.CanvasSizePixelsSec, 
                //Html.DisplayFor(model => model.Canvas.Name),
                Model.Canvas.Width, 
                Model.Canvas.Height,
                Html.DisplayNameFor(model => fs.MaxIdleInterval),
                maxInterval
                ))
        }
        else
        {
            @(string.Format(Resources.CanvasPositionSizePixels, 
                //Html.DisplayFor(model => model.Canvas.Name),
                Model.Left, 
                Model.Top, 
                Model.Width, 
                Model.Height
                ))
        }
    </div>
    </div>
    </div>
        </td>
        <td class="preview">
            <div id="canvas" data-path="@Html.Raw(Url.Action("Data", "Canvas"))">
                <div>
                    <img src="@Html.Raw(Url.Action("Thumb", "Media", new { id="nnn", width="qqq", height="qqq" }))" alt="Background" />
                </div>
            </div>
        </td>
    </tr></table>
</fieldset>