Management/Models/Annotations/Display.cs
using DisplayMonkey.Language;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DisplayMonkey.Models
{
    [
        MetadataType(typeof(Display.Annotations))
    ]
    public partial class Display
    {
        public Display(DisplayMonkeyEntities _db, int _canvasId, int _locationId)
        {
            CanvasId = _canvasId;
            LocationId = _locationId;
            init(_db);
        }

        public Display() { }
        
        protected void init(DisplayMonkeyEntities _db)
        {
            Setting readyTimeout = Setting.GetSetting(_db, Setting.Keys.DefaultDisplayReadyEventTimeout);
            if (readyTimeout != null)
            {
                this.ReadyTimeout = readyTimeout.IntValuePositive;
            }

            Setting errorLength = Setting.GetSetting(_db, Setting.Keys.DefaultDisplayErrorLength);
            if (errorLength != null)
            {
                this.ErrorLength = errorLength.IntValuePositive;
            }

            Setting pollInterval = Setting.GetSetting(_db, Setting.Keys.DefaultDisplayPollInterval);
            if (pollInterval != null)
            {
                this.PollInterval = pollInterval.IntValuePositive;
            }
        }

        internal class Annotations
        {
            [
                Display(ResourceType = typeof(Resources), Name = "ID"),
            ]
            public int DisplayId { get; set; }

            [
                Display(ResourceType = typeof(Resources), Name = "Canvas"),
            ]
            public int CanvasId { get; set; }

            [
                Display(ResourceType = typeof(Resources), Name = "Location"),
            ]
            public int LocationId { get; set; }

            [
                Display(ResourceType = typeof(Resources), Name = "Name"),
                Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "NameRequired"),
                StringLength(100, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "MaxLengthExceeded"),
            ]
            public string Name { get; set; }

            [
                Display(ResourceType = typeof(Resources), Name = "Host"),
            ]
            public string Host { get; set; }

            [
                Display(ResourceType = typeof(Resources), Name = "ErrorLength"),
                Range(0, Int32.MaxValue,
                    ErrorMessageResourceType = typeof(Resources),
                    ErrorMessageResourceName = "PositiveIntegerRequired"),
            ]
            public int ErrorLength { get; set; }

            [
                Display(ResourceType = typeof(Resources), Name = "PollInterval"),
                Range(1, Int32.MaxValue,
                    ErrorMessageResourceType = typeof(Resources),
                    ErrorMessageResourceName = "PositiveIntegerRequired"),
            ]
            public int PollInterval { get; set; }

            [
                Display(ResourceType = typeof(Resources), Name = "NoScroll"),
            ]
            public bool NoScroll { get; set; }

            [
                Display(ResourceType = typeof(Resources), Name = "NoCursor"),
            ]
            public bool NoCursor { get; set; }

            [
                Display(ResourceType = typeof(Resources), Name = "Canvas"),
            ]
            public virtual Canvas Canvas { get; set; }

            [
                Display(ResourceType = typeof(Resources), Name = "Location"),
            ]
            public virtual Location Location { get; set; }

            [
                Display(ResourceType = typeof(Resources), Name = "ReadyTimeout"),
                Range(1, Int32.MaxValue,
                    ErrorMessageResourceType = typeof(Resources),
                    ErrorMessageResourceName = "PositiveIntegerRequired"),
            ]
            public int ReadyTimeout { get; set; }

            [
                Display(ResourceType = typeof(Resources), Name = "RecycleTime"),
            ]
            public Nullable<System.TimeSpan> RecycleTime { get; set; }
        }

        [
            NotMapped,
            Display(ResourceType = typeof(Resources), Name = "RecycleTime"),
        ]
        public string AutoRefreshAt
        {
            get
            {
                string x = null;
                if (this.RecycleTime.HasValue)
                    x = this.RecycleTime.Value.ToString(@"h\:mm");
                return x;
            }

            set
            {
                TimeSpan x;
                if (TimeSpan.TryParse(value, out x))
                    this.RecycleTime = x;
                else
                    this.RecycleTime = null;
            }
        }
    }
}

Management/Models/Display.cs
/*!
* DisplayMonkey source file
* http://displaymonkey.org
*
* Copyright (c) 2019 Fuel9 LLC and contributors
*
* Released under the MIT license:
* http://opensource.org/licenses/MIT
*/

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayMonkey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Display
    {
        public int DisplayId { get; set; }
        public string Name { get; set; }
        public string Host { get; set; }
        public int CanvasId { get; set; }
        public int LocationId { get; set; }
        public byte[] Version { get; set; }
        public bool NoScroll { get; set; }
        public int ReadyTimeout { get; set; }
        public int PollInterval { get; set; }
        public int ErrorLength { get; set; }
        public bool NoCursor { get; set; }
        public Nullable<System.TimeSpan> RecycleTime { get; set; }
    
        public virtual Canvas Canvas { get; set; }
        public virtual Location Location { get; set; }
    }
}

Management/Controllers/DisplayController.cs
/*!
* DisplayMonkey source file
* http://displaymonkey.org
*
* Copyright (c) 2015 Fuel9 LLC and contributors
*
* Released under the MIT license:
* http://opensource.org/licenses/MIT
*/

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using DisplayMonkey.Models;

namespace DisplayMonkey.Controllers
{
    public class DisplayController : BaseController
    {
        private DisplayMonkeyEntities db = new DisplayMonkeyEntities();

        private void FillCanvasSelectList(object selected = null)
        {
            var list = db.Canvases
                .OrderBy(c => c.Name)
                .ToList()
                ;

            ViewBag.Canvases = new SelectList(list, "CanvasId", "Name", selected);
        }

        private void FillLocationSelectList(object selected = null)
        {
            var list = db.Locations
                .AsEnumerable()
                .Select(l => new
                {
                    LocationId = l.LocationId,
                    Name = l.Area == null ? 
                        string.Format("{0} : {1}", l.Level.Name, l.Name) :
                        string.Format("{0} : {1} : {2}", l.Level.Name, l.Area.Name, l.Name),
                })
                .OrderBy(l => l.Name)
                .ToList()
                ;

            ViewBag.Locations = new SelectList(list, "LocationId", "Name", selected);
        }

        //
        // GET: /Display/

        public ActionResult Index(int canvasId = 0, int locationId = 0, string name = null, string host = null)
        {
            IQueryable<Display> displays = db.Displays
                .Include(d => d.Canvas)
                .Include(d => d.Location)
                .OrderBy(d => d.Name)
                ;

            if (canvasId > 0)
            {
                displays = displays
                    .Where(d => d.CanvasId == canvasId)
                    ;
            }

            if (locationId > 0)
            {
                IEnumerable<int> tree = db.Locations
                    .Find(locationId)
                    .SelfAndChildren
                    .Select(l => l.LocationId)
                    ;
                
                displays = displays
                    .Where(d => tree.Contains(d.LocationId))
                    ;
            }

            if (!string.IsNullOrEmpty(name))
            {
                displays = displays
                    .Where(d => d.Name.Contains(name))
                    ;
            }

            if (!string.IsNullOrEmpty(host))
            {
                displays = displays
                    .Where(d => d.Host.Contains(host))
                    ;
            }

            FillCanvasSelectList(canvasId);
            FillLocationSelectList(locationId);
            
            return View(displays.ToList());
        }

        //
        // GET: /Display/Browse/5

        public ActionResult Browse(int id = 0)
        {
            string path = Setting.GetSetting(db, Setting.Keys.PresentationSite).StringValue;

            if (string.IsNullOrWhiteSpace(path))
            {
                string site = ConfigurationManager.AppSettings["presentationSite"];
                if (string.IsNullOrEmpty(site)) site = Request.Url.DnsSafeHost;

                string root = ConfigurationManager.AppSettings["presentationRoot"];
                if (string.IsNullOrEmpty(root)) root = "";

                path = string.Format(
                    "http://{0}/{1}",
                    site,
                    root
                    );
            }

            if (!path.EndsWith("/")) path += "/";
            
            string url = string.Format(
                "{0}getCanvas.aspx?display={1}",
                path,
                id
                );
            return Redirect(url);
        }

        //
        // GET: /Display/Create

        public ActionResult Create(int canvasId = 0, int locationId = 0)
        {
            Display display = new Display(db, canvasId, locationId);

            FillCanvasSelectList(display.CanvasId);
            FillLocationSelectList(display.LocationId);

            return View(display);
        }

        //
        // POST: /Display/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Display display)
        {
            if (ModelState.IsValid)
            {
                db.Displays.Add(display);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            FillCanvasSelectList(display.CanvasId);
            FillLocationSelectList(display.LocationId);

            return View(display);
        }

        //
        // GET: /Display/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Display display = db.Displays.Find(id);
            if (display == null)
            {
                return View("Missing", new MissingItem(id));
            }

            FillCanvasSelectList(display.CanvasId);
            FillLocationSelectList(display.LocationId);

            return View(display);
        }

        //
        // POST: /Display/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Display display)
        {
            if (ModelState.IsValid)
            {
                db.Entry(display).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            FillCanvasSelectList(display.CanvasId);
            FillLocationSelectList(display.LocationId);

            return View(display);
        }

        //
        // GET: /Display/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Display display = db.Displays.Find(id);
            if (display == null)
            {
                return View("Missing", new MissingItem(id));
            }
            return View(display);
        }

        //
        // POST: /Display/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Display display = db.Displays.Find(id);
            db.Displays.Remove(display);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Management/Views/Display/Create.cshtml
    @model DisplayMonkey.Models.Display

@{
    ViewBag.Title = Resources.AddDisplay;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.Referrer()

    <fieldset>
        <legend>@Resources.Display</legend>

        @Html.Partial("_Edit")

        <p>
            <input type="submit" value="@Resources.Add" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink(Resources.ViewDisplays, "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Management/Views/Display/Delete.cshtml
@model DisplayMonkey.Models.Display

@{
    ViewBag.Title = Resources.RemoveDisplay;
}

<h2>@ViewBag.Title</h2>

<h3>@Resources.AreYouSureYouWantToRemoveThisDisplay</h3>
<fieldset>
    <legend>@Resources.Display</legend>

    <div class="divTable">
    <div class="divRow">
    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
    </div>

    <div class="divRow">
    <div class="display-label">
         @Html.DisplayNameFor(model => model.Host)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Host)
    </div>
    </div>

    <div class="divRow">
    <div class="display-label">
         @Html.DisplayNameFor(model => model.Canvas)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Canvas.Name)
    </div>
    </div>

    <div class="divRow">
    <div class="display-label">
         @Html.DisplayNameFor(model => model.Location)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Location.Name)
    </div>
    </div>

    <div class="divRow">
    <div class="display-label">
         @Html.DisplayNameFor(model => model.ErrorLength)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ErrorLength)
    </div>
    </div>

    <div class="divRow">
    <div class="display-label">
         @Html.DisplayNameFor(model => model.PollInterval)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PollInterval)
    </div>
    </div>

    <div class="divRow">
    <div class="display-label">
         @Html.DisplayNameFor(model => model.NoScroll)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NoScroll)
    </div>
    </div>

    <div class="divRow">
    <div class="display-label">
         @Html.DisplayNameFor(model => model.NoCursor)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NoCursor)
    </div>
    </div>

    <div class="divRow">
    <div class="display-label">
         @Html.DisplayNameFor(model => model.ReadyTimeout)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ReadyTimeout) @Resources.Sec
    </div>
    </div>

    <div class="divRow">
    <div class="display-label">
         @Html.DisplayNameFor(model => model.AutoRefreshAt)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AutoRefreshAt)
    </div>
    </div>
    
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.Referrer()
    <p>
        <input type="submit" value="@Resources.Remove" /> |
        @Html.ActionLink(Resources.ViewDisplays , "Index")
    </p>
}

Management/Views/Display/Edit.cshtml
@model DisplayMonkey.Models.Display

@{
    ViewBag.Title = Resources.EditDisplay;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.Referrer()

    <fieldset>
        <legend>@Resources.Display</legend>

        @Html.HiddenFor(model => model.DisplayId)

        @Html.Partial("_Edit")

        <p>
            <input type="submit" value="@Resources.Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink(Resources.ViewDisplays, "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Management/Views/Display/Index.cshtml
@model IEnumerable<DisplayMonkey.Models.Display>

@{
    ViewBag.Title = Resources.Displays;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Index", "Display", FormMethod.Get))
{    
    <fieldset><legend>Search</legend><table>
        <tr><td>Canvas:</td><td><div class="select">@Html.DropDownList("CanvasId", ViewBag.Canvases as SelectList, Resources.Any)</div></td></tr>
        <tr><td>Vị trí:</td><td><div class="select">@Html.DropDownList("LocationId", ViewBag.Locations as SelectList, Resources.Any)</div></td></tr>
        <tr><td>Tên:</td><td>@Html.TextBox("name")</td></tr>
        <tr><td>Địa chỉ IP:</td><td>@Html.TextBox("host")</td></tr>
    <tr><td colspan="2"><input type="submit" value="@Resources.Filter" /></td></tr></table></fieldset> 
}

<p>
    @Html.ActionLink(Resources.AddDisplay, "Create")
</p>
<table class="grid">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Host)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Canvas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.Name, "Browse", new { id = item.DisplayId }, new { target = "_blank", title = Resources.BrowseDisplay })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Host)
        </td>
        <td>
            @Html.ActionLink(item.Canvas.Name, "Details", "Canvas", new { id = item.CanvasId }, null)
        </td>
        <td>
            @Html.ActionLink(item.Location.Name, "Details", "Location", new { id = item.LocationId }, null)
        </td>
        <td>
            @Html.ActionLink(Resources.Edit, "Edit", new { id=item.DisplayId }) |
            @Html.ActionLink(Resources.Delete, "Delete", new { id=item.DisplayId })
        </td>
    </tr>
}

</table>

Management/Views/Display/_Edit.cshtml
@model DisplayMonkey.Models.Display

@{
    SelectList autoLoadModes = ViewBag.AutoLoadModes as SelectList;
}

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Host)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Host)
            @Html.ValidationMessageFor(model => model.Host)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Canvas)
        </div>
        <div class="editor-field select">
            @Html.DropDownList("CanvasId", ViewBag.Canvases as SelectList)
            @Html.ValidationMessageFor(model => model.CanvasId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Location)
        </div>
        <div class="editor-field select">
            @Html.DropDownList("LocationId", ViewBag.Locations as SelectList)
            @Html.ValidationMessageFor(model => model.LocationId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ErrorLength)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ErrorLength, new { htmlAttributes = new { @class = "duration" } }) @Resources.Sec
            @Html.ValidationMessageFor(model => model.ErrorLength)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PollInterval)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PollInterval, new { htmlAttributes = new { @class = "duration" } }) @Resources.Sec
            @Html.ValidationMessageFor(model => model.PollInterval)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NoScroll)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NoScroll)
            @Html.ValidationMessageFor(model => model.NoScroll)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NoCursor)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NoCursor)
            @Html.ValidationMessageFor(model => model.NoCursor)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ReadyTimeout)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ReadyTimeout, new { htmlAttributes = new { @class = "duration" } }) @Resources.Sec
            @Html.ValidationMessageFor(model => model.ReadyTimeout)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AutoRefreshAt)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AutoRefreshAt, new { htmlAttributes = new { @class = "timepicker duration" } })
            @Html.ValidationMessageFor(model => model.AutoRefreshAt)
        </div>

        <script type="text/javascript">
            $(document).ready(function () {
                $('input.timepicker').timepicker({
                    'timeFormat': 'G:i',
                    'show2400': false,
                    'noneOption': '@Resources.Never'
                });
            });
        </script>