Management/Controllers/HtmlController.cs
/*!
* DisplayMonkey source file
* http://displaymonkey.org
*
* Copyright (c) 2015 Fuel9 LLC and contributors
*
* Released under the MIT license:
* http://opensource.org/licenses/MIT
*/

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
//using System.Net;
using System.Web;
using System.Web.Mvc;
using DisplayMonkey.Models;

namespace DisplayMonkey.Controllers
{
    public class HtmlController : BaseController
    {
        private DisplayMonkeyEntities db = new DisplayMonkeyEntities();

        // GET: /Html/Details/5
        public ActionResult Details(int id = 0)
        {
            Html html = db.Frames.Find(id) as Html;
            if (html == null)
            {
                return View("Missing", new MissingItem(id));
            }
            return View(html);
        }

        // GET: /Html/Create
        public ActionResult Create()
        {
            Frame frame = TempData[FrameController.SelectorFrameKey] as Frame;

            if (frame == null || frame.PanelId == 0)
            {
                return RedirectToAction("Create", "Frame");
            }

            Html html = new Html(frame, db)
            {
                Panel = db.Panels
                    .Include(p => p.Canvas)
                    .FirstOrDefault(p => p.PanelId == frame.PanelId),
            };

            this.FillTemplatesSelectList(db, FrameTypes.Html);
            
            return View(html);
        }

        // POST: /Html/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(Html html)
        {
            if (ModelState.IsValid)
            {
                db.Frames.Add(html);
                db.SaveChanges();

                return RedirectToAction("Index", "Frame");
            }

            html.Panel = db.Panels
                .Include(p => p.Canvas)
                .FirstOrDefault(p => p.PanelId == html.PanelId)
                ;

            this.FillTemplatesSelectList(db, FrameTypes.Html, html.TemplateId);
            
            return View(html);
        }

        // GET: /Html/Edit/5
        public ActionResult Edit(int id = 0)
        {
            Html html = db.Frames.Find(id) as Html;
            if (html == null)
            {
                return View("Missing", new MissingItem(id));
            }

            this.FillTemplatesSelectList(db, FrameTypes.Html, html.TemplateId);

            return View(html);
        }

        // POST: /Html/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(Html html)
        {
            if (ModelState.IsValid)
            {
                db.Entry(html).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index", "Frame");
            }


            this.FillTemplatesSelectList(db, FrameTypes.Html, html.TemplateId);
            
            return View(html);
        }

        // GET: /Html/Delete/5
        public ActionResult Delete(int id = 0)
        {
            Html html = db.Frames.Find(id) as Html;
            if (html == null)
            {
                return View("Missing", new MissingItem(id));
            }

            return View(html);
        }

        //
        // GET: /Media/Preview/5

        //[Authorize]
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Preview(int id)
        {
            Html html = db.Frames.Find(id) as Html;
            if (html == null)
            {
                return HttpNotFound();
            }

            return Content(html.Content);
        }

        // POST: /Html/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Frame frame = db.Frames.Find(id);
            db.Frames.Remove(frame);
            db.SaveChanges();

            return RedirectToAction("Index", "Frame");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Management/Views/Html/Create.cshtml
@model DisplayMonkey.Models.Html

@{
    ViewBag.Title = Resources.CreateNewHtmlFrame;
    DisplayMonkey.Models.Canvas cvs = Model.Panel.Canvas;
    string bg = string.Format("background-color:{0};", cvs.BackgroundColor);
    if (cvs.BackgroundImage != null)
    {
        bg += string.Format("background-image:url('{0}');background-position:{1}px {2}px;",
            Html.Raw(Url.Action("Thumb", "Media", new { id = cvs.BackgroundImage, width = cvs.Width, height = cvs.Height })),
            -Model.Panel.Left,
            -Model.Panel.Top
            );
    }
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.Referrer()

    @Html.Partial("_frameData", Model as Frame)
    @Html.Partial("_Edit")

    <p>
        <input type="submit" value="@Resources.Create" />
    </p>
}

<div>
    @Html.ActionLink(Resources.ViewFrames, "Index", "Frame")
</div>

@section Styles {
    @Styles.Render("~/Content/cleditorcss")
}

@section Scripts {
    @Scripts.Render("~/bundles/cleditor")

    <script type="text/javascript">
        $(document).ready(function () {
            //var x = jHtmlArea.defaultOptions;
            //x.toolbar.push(["forecolor"]);
            //$("textarea").htmlarea(x);
            $("textarea").cleditor({ bodyStyle: "@bg" });
        });
    </script>
}

Management/Views/Html/Delete.cshtml
@model DisplayMonkey.Models.Html

@{
    ViewBag.Title = Resources.DeleteHtmlFrame;
}

<h2>@ViewBag.Title</h2>

<h3>@Resources.AreYouSureYouWantToDeleteThisFrame</h3>

@Html.Partial("_Details")

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.Referrer()
    <p>
        <input type="submit" value="@Resources.Delete" /> |
        @Html.ActionLink(Resources.ViewFrames, "Index", "Frame")
    </p>
}

Management/Views/Html/Details.cshtml
@model DisplayMonkey.Models.Html

@{
    ViewBag.Title = Resources.HtmlFrameDetails;
}

<h2>@ViewBag.Title</h2>

@Html.Partial("_Details")

<p>
    @Html.ActionLink(Resources.Edit, "Edit", "Frame", new { id=Model.FrameId }, null) |
    @Html.ActionLink(Resources.ViewFrames, "Index", "Frame")
</p>

@Html.Partial("_frameLocations", Model as Frame)

Management/Views/Html/Edit.cshtml
@model DisplayMonkey.Models.Html

@{
    ViewBag.Title = Resources.EditHtmlFrame;
    DisplayMonkey.Models.Canvas cvs = Model.Panel.Canvas;
    string bg = string.Format("background-color:{0};", cvs.BackgroundColor);
    if (cvs.BackgroundImage != null)
    {
        bg += string.Format("background-image:url('{0}');background-position:{1}px {2}px;",
            Html.Raw(Url.Action("Thumb", "Media", new { id = cvs.BackgroundImage, width = cvs.Width, height = cvs.Height })),
            -Model.Panel.Left,
            -Model.Panel.Top
            );
    }
}


<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.Referrer()

    @Html.Partial("_frameData", Model as Frame)
    @Html.Partial("_Edit")

    <p>
        <input type="submit" value="@Resources.Save" />
    </p>
}

<div>
    @Html.ActionLink(Resources.ViewFrames, "Index", "Frame")
</div>

@section Styles {
    @Styles.Render("~/Content/cleditorcss")
}

@section Scripts {
    @Scripts.Render("~/bundles/cleditor")

    <script type="text/javascript">
        $(document).ready(function () {
            //var x = jHtmlArea.defaultOptions;
            //x.toolbar.push(["forecolor"]);
            //$("textarea").htmlarea(x);
            $("textarea").cleditor({ bodyStyle: "@bg" });
        });
    </script>
}

Management/Views/Html/_Details.cshtml
@model DisplayMonkey.Models.Html

@{
    DisplayMonkey.Models.Canvas cvs = Model.Panel.Canvas;
    string bg = string.Format("background-color:{0};", cvs.BackgroundColor);
    if (cvs.BackgroundImage != null)
    {
        bg += string.Format("background-image:url('{0}');background-position:{1}px {2}px;",
            Html.Raw(Url.Action("Thumb", "Media", new { id = cvs.BackgroundImage, width = cvs.Width, height = cvs.Height })),
            -Model.Panel.Left,
            -Model.Panel.Top
            );
    }
}

    <table class="divTable"><tr>
        <td>

            @Html.Partial("_frameDetails", Model as Frame)

            <fieldset>
                <legend>@Resources.Html</legend>

                <div class="divTable">

                <div class="divRow">
                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Name)
                </div>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Name)
                </div>
                </div>

                </div>
            
            </fieldset>
        
        </td>

        <td>
            <div class="preview">
                <iframe style="@bg" src="@Url.Action("Preview", "Html", new { id = Model.FrameId })" id="htmlPreview" sandbox="allow-scripts"></iframe>
            </div>
        </td>

    </tr></table>

Management/Views/Html/_Edit.cshtml
@model DisplayMonkey.Models.Html

    <fieldset>
        <legend>@Resources.Html</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Content)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Content, new {@class = "htmlEdit"})
            @Html.ValidationMessageFor(model => model.Content)
        </div>

    </fieldset>

Management/Views/Html/_Film.cshtml
@model DisplayMonkey.Models.Html

<div class="d1">
    <div><img src="~/images/html.png" alt="" /></div>
    <div>@(string.Format("{0}, {1} {2}", Model.FrameType, Model.Duration, Resources.Sec))</div>
</div>
<div>
    @Html.ShortSpan(Model.Name, 17)
</div>

Management/Views/Html/_Summary.cshtml
@model DisplayMonkey.Models.Html

@Resources.Name@(": ")<span>@Model.Name</span>