Management/Models/Frame.cs
/*!
* DisplayMonkey source file
* http://displaymonkey.org
*
* Copyright (c) 2019 Fuel9 LLC and contributors
*
* Released under the MIT license:
* http://opensource.org/licenses/MIT
*/

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayMonkey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frame
    {
        public Frame()
        {
            this.Locations = new HashSet<Location>();
        }
    
        public int FrameId { get; set; }
        public int PanelId { get; set; }
        public int Duration { get; set; }
        public Nullable<System.DateTime> BeginsOn { get; set; }
        public Nullable<System.DateTime> EndsOn { get; set; }
        public Nullable<int> Sort { get; set; }
        public System.DateTime DateCreated { get; protected set; }
        public byte[] Version { get; protected set; }
        public int TemplateId { get; set; }
        public int CacheInterval { get; set; }
    
        public virtual Panel Panel { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual Template Template { get; set; }
    }
}

Management/Controllers/FrameController.cs
/*!
* DisplayMonkey source file
* http://displaymonkey.org
*
* Copyright (c) 2015 Fuel9 LLC and contributors
*
* Released under the MIT license:
* http://opensource.org/licenses/MIT
*/

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DisplayMonkey.Models;

namespace DisplayMonkey.Controllers
{
    public class FrameController : BaseController
    {
        private DisplayMonkeyEntities db = new DisplayMonkeyEntities();

        public const string SelectorFrameKey = "_selectorFrame";

        private void FillCanvasesSelectList(object selected = null)
        {
            var query = from c in db.Canvases
                        orderby c.Name
                        select c;
            ViewBag.CanvasId = new SelectList(query, "CanvasId", "Name", selected);
        }

        private class PanelSelectListItem
        {
            public int id { get; set; }
            public string name { get; set; }
            //public bool selected { get; set; }
        }

        private IQueryable<PanelSelectListItem> GetPanelsForCanvas(int canvasId = 0 /*, int panelId = 0*/)
        {
            IQueryable<Panel> list = db.Panels;

            if (canvasId > 0)
            {
                return db.Panels
                    .Where(p => p.CanvasId == canvasId)
                    .Select(p => new PanelSelectListItem { 
                        id = p.PanelId, 
                        name = p.Name, 
                        //selected = p.PanelId == panelId 
                    })
                    .OrderBy(p => p.name)
                    ;
            }
            else
            {
                return db.Panels
                    .Select(p => new PanelSelectListItem { 
                        id = p.PanelId,
                        name = canvasId == 0 ? p.Canvas.Name + " : " + p.Name : p.Name,
                        //selected = p.PanelId == panelId 
                    })
                    .OrderBy(p => p.name)
                    ;
            }
        }

        private void FillPanelsSelectList(object selected = null, int canvasId = 0)
        {
            ViewBag.PanelId = new SelectList(GetPanelsForCanvas(canvasId).AsEnumerable(), "id", "name", selected);
        }

        private void FillFrameTypeSelectList(FrameTypes? selected = null)
        {
            ViewBag.FrameType = selected.TranslatedSelectList(valueAsText: true);
        }

        private void FillTimingOptionsSelectList(Frame.TimingOptions? selected = null)
        {
            ViewBag.TimingOption = selected.TranslatedSelectList(valueAsText: false);
        }


        //
        // GET: /PanelsForCanvas/5

        public JsonResult PanelsForCanvas(int /*canvas*/ id = 0)
        {
            return Json(GetPanelsForCanvas(id).ToList(), JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /Frame/

        public ActionResult Index(int canvasId = 0, int panelId = 0, FrameTypes? frameType = null, int? timingOption = null /*, int page = 1*/)
        {
            //if (page <= 0) page = 1;

            IQueryable<Frame> list = db.Frames
                .Include(f => f.Panel)
                .Include(f => f.Panel.Canvas)
                ;

            if (canvasId > 0)
            {
                list = list.Where(f => f.Panel.CanvasId == canvasId);
            }

            if (panelId > 0)
            {
                list = list.Where(f => f.PanelId == panelId);
            }

            if (frameType != null)
            {
                list = list.Where(Frame.FilterByFrameType(frameType));
            }

            DateTime dt = DateTime.Now;
            if (timingOption != null)
            {
                switch ((Frame.TimingOptions)timingOption)
                {
                    case Frame.TimingOptions.TimingOption_Pending:
                        list = list.Where(f => dt < f.BeginsOn);
                        break;

                    case Frame.TimingOptions.TimingOption_Current:
                        list = list.Where(f => (f.BeginsOn == null || f.BeginsOn <= dt) && (f.EndsOn == null || dt < f.EndsOn));
                        break;

                    case Frame.TimingOptions.TimingOption_Expired:
                        list = list.Where(f => f.EndsOn <= dt);
                        break;
                }
            }

            //ViewBag.TotalPages = (int)Math.Ceiling((float)list.Count() / 20.0);
            //ViewBag.CurrentPage = page;

            list = list
                //.Skip((page - 1) * 20)
                //.Take(20)
                .OrderBy(f => f.Panel.Canvas.Name)
                .ThenBy(f => f.Panel.Name)
                .ThenBy(f => f.Sort == null ? (float)f.FrameId : (float)f.Sort)
                .ThenBy(f => f.FrameId)
                ;

            FillCanvasesSelectList(canvasId);
            FillPanelsSelectList(panelId, canvasId);
            FillFrameTypeSelectList(frameType);
            FillTimingOptionsSelectList((Frame.TimingOptions?)timingOption);
             
            return View(list.ToList());
        }

        //
        // GET: /Frame/Create

        public ActionResult Create(int canvasId = 0, int panelId = 0, FrameTypes? frameType = null)
        {
            Panel panel = null;
            if (panelId != 0)
            {
                panel = db.Panels
                    .Include(p => p.Canvas)
                    .FirstOrDefault(p => p.PanelId == panelId)
                    ;

                if (panel == null)
                    panelId = 0;
            }
            
            if (frameType == null || panel == null)
            {
                if (canvasId == 0 && panel != null)
                    canvasId = panel.CanvasId;
                
                return RedirectToAction("ForFrameType", new { 
                    canvasId = canvasId, 
                    panelId = panelId, 
                    frameType = frameType
                });
            }

            TempData[SelectorFrameKey] = new Frame()
            {
                Panel = panel,
                PanelId = panelId,
                CacheInterval = 0,
            };

            return RedirectToAction("Create", frameType.ToString());
        }

        public ActionResult ForFrameType(int canvasId = 0, int panelId = 0, FrameTypes? frameType = null)
        {
            if (canvasId == 0)
            {
                Canvas canvas = db.Canvases
                    .OrderBy(c => c.Name)
                    .FirstOrDefault()
                    ;

                if (canvas != null)
                    canvasId = canvas.CanvasId;
            }
            
            FrameSelector selector = new FrameSelector() 
            { 
                CanvasId = canvasId,
                PanelId = panelId,
                FrameType = frameType.HasValue ? frameType.Value : 0,
            };

            FillCanvasesSelectList(canvasId);
            FillPanelsSelectList(panelId, canvasId);
            FillFrameTypeSelectList(frameType);
            return View(selector);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ForFrameType([Bind(Include = "CanvasId,PanelId,FrameType")] FrameSelector selector)
        {
            PushReferrer();

            if (selector.PanelId != 0 && selector.FrameType != null)
            {
                Panel panel = db.Panels
                    .Include(p => p.Canvas)
                    .FirstOrDefault(p => p.PanelId == selector.PanelId)
                    ;

                selector.Panel = panel;
                //selector.CacheInterval = 0;

                TempData[SelectorFrameKey] = selector;
                return RedirectToAction("Create", selector.FrameType.ToString());
            }

            return RedirectToAction("ForFrameType", new { 
                canvasId = selector.CanvasId, 
                panelId = selector.PanelId, 
                frameType = selector.FrameType 
            });
        }

        //
        // GET: /Frame/Details/5

        public ActionResult Details(int id = 0)
        {
            Frame frame = db.Frames
                .Where( f => f.FrameId == id)
                .Include(f => f.Panel)
                .Include(f => f.Panel.Canvas)
                .FirstOrDefault()
                ;

            if (frame == null)
            {
                return View("Missing", new MissingItem(id));
            }

            return RedirectToAction("Details", frame.FrameType.ToString(), new { id = id });
        }

        //
        // GET: /Frame/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Frame frame = db.Frames
                .Where(f => f.FrameId == id)
                .Include(f => f.Panel)
                .Include(f => f.Panel.Canvas)
                .FirstOrDefault()
                ;

            if (frame == null)
            {
                return View("Missing", new MissingItem(id));
            }

            return RedirectToAction("Edit", frame.FrameType.ToString(), new { id = id });
        }

        //
        // GET: /Frame/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Frame frame = db.Frames
                .Where(f => f.FrameId == id)
                .Include(f => f.Panel)
                .Include(f => f.Panel.Canvas)
                .FirstOrDefault()
                ;

            if (frame == null)
            {
                return View("Missing", new MissingItem(id));
            }

            return RedirectToAction("Delete", frame.FrameType.ToString(), new { id = id });
        }

        //
        // GET: /Frame/Attach/5

        public ActionResult Attach(int id = 0)
        {
            Frame frame = db.Frames.Find(id);
            if (frame == null)
            {
                return View("Missing", new MissingItem(id));

Management/Views/Frame/Attach.cshtml
@model DisplayMonkey.Models.LocationSelector

@{
    ViewBag.Title = Resources.DesignateLocation;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.Referrer()

    <fieldset>
        <legend>@Resources.Frame</legend>

        @Html.HiddenFor(m => m.FrameId)
        
        <div class="editor-label">
            @Html.LabelFor(l => l.LocationId)
        </div>
        <div class="editor-field select">
            @Html.DropDownListFor(l => l.LocationId, ViewBag.Locations as SelectList)
        </div>

        <p>
            <input type="submit" value="@Resources.Designate" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink(Resources.ViewFrames, "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Management/Views/Frame/Detach.cshtml
@model DisplayMonkey.Models.LocationSelector

@{
    ViewBag.Title = Resources.RemoveLocation;
}

<h2>@ViewBag.Title</h2>

<h3>@Resources.AreYouSureYouWantToRemoveLocationFromThisFrame</h3>
<fieldset>
    <legend>@Resources.Frame</legend>

    @Html.HiddenFor(m => m.FrameId)
    @Html.HiddenFor(m => m.LocationId)

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LocationName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LocationName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.Referrer()
    <p>
        <input type="submit" value="@Resources.Remove" /> |
        @Html.ActionLink(Resources.ViewFrames, "Index")
    </p>
}

Management/Views/Frame/ForCanvas.cshtml
@model DisplayMonkey.Models.Canvas

@{
    ViewBag.Title = Resources.CreateNewFrame;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.Referrer()

    <fieldset>
        <legend>@Resources.NewFrame</legend>

        <div class="editor-label">
            @Html.Label(Resources.SelectCanvas)
        </div>
        <div class="editor-field select">
            @Html.DropDownListFor(c => c.CanvasId, ViewBag.CanvasId as SelectList)
        </div>
        <p>
            <input type="submit" value="@Resources.Next" />
        </p>
    </fieldset>
}

Management/Views/Frame/ForFrameType.cshtml
@model DisplayMonkey.Models.FrameSelector

@{
    ViewBag.Title = Resources.CreateNewFrame;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.Referrer()

    <fieldset>
        <legend>@Resources.Frame</legend>

        <div class="editor-label">
            @Html.Label(Resources.SelectCanvas)
        </div>
        <div class="editor-field select">
            @Html.DropDownListFor(c => c.CanvasId, ViewBag.CanvasId as SelectList)
        </div>

        <div class="editor-label">
            @Html.Label(Resources.SelectPanel)
        </div>
        <div class="editor-field select">
            @Html.DropDownListFor(p => p.PanelId, ViewBag.PanelId as SelectList)
        </div>

        <div class="editor-label">
            @Html.Label(Resources.SelectFrameType)
        </div>
        <div class="editor-field select">
            @Html.DropDownListFor(s => s.FrameType, ViewBag.FrameType as SelectList)
        </div>

        <p>
            <input type="submit" value="@Resources.Next" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink(Resources.ViewFrames, "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        function fillPanels () {
            var canvasId = $('select#CanvasId').val() || 0;
            $.ajax({
                url: url = "@Url.Action("PanelsForCanvas", "Frame")/" + canvasId,
            })
            .done(function (data) {
                var panels = $("select#PanelId"), v = panels.val();
                panels.children().each(function (i, p) {
                    $(p).remove();
                });
                $(data).each(function (i, p) {
                    panels.append('<option value="' + p.id + (p.id == v ? '" selected>' : '">') + p.name + '</option>');
                });
            });
        };
        $(document).ready(function () {
            $('select#CanvasId').change(function () {
                fillPanels();
            });
        });
    </script>
}

Management/Views/Frame/ForPanel.cshtml
@model DisplayMonkey.Models.Panel

@{
    ViewBag.Title = Resources.CreateNewFrame;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.Referrer()

    <fieldset>
        <legend>@Resources.NewFrame</legend>

        <div class="editor-label">
            @Html.LabelFor(p => p.Canvas)
        </div>
        <div class="editor-field">
            @Html.DisplayFor(p => p.Canvas.Name)
        </div>
        <div class="editor-label">
            @Html.Label(Resources.SelectPanel)
        </div>
        <div class="editor-field select">
            @Html.DropDownListFor(p => p.PanelId, ViewBag.PanelId as SelectList)
        </div>
        <p>
            <input type="submit" value="@Resources.Next" />
        </p>
    </fieldset>
}

Management/Views/Frame/Index.cshtml
@model IEnumerable<DisplayMonkey.Models.Frame>

@{
    ViewBag.Title = Resources.Frames;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Index", "Frame", FormMethod.Get))
{    
    <fieldset><legend>@Resources.Search</legend><table>
        <tr><td>@Resources.Canvas:</td><td><div class="select">@Html.DropDownList("CanvasId",Resources.Any)</div></td></tr>
        <tr><td>@Resources.Panel:</td><td><div class="select">@Html.DropDownList("PanelId", Resources.Any)</div></td></tr>
        <tr><td>@Resources.FrameType:</td><td><div class="select">@Html.DropDownList("FrameType",Resources.Any)</div></td></tr>
        <tr><td>@Resources.TimingOption:</td><td><div class="select">@Html.DropDownList("TimingOption",Resources.Any)</div></td></tr>
    <tr><td colspan="2"><input type="submit" value="@Resources.Filter" /></td></tr></table></fieldset> 
}

@Html.ActionLink(Resources.CreateNewFrame, "Create", new { canvasId = Request["canvasId"], panelId = Request["panelId"], frameType = Request["frameType"] })

@Html.Partial("_frameList", Model)

@section Scripts {
    <script type="text/javascript">
        function fillPanels () {
            var canvasId = $('select#CanvasId').val() || 0;
            $.ajax({
                url: url = "@Url.Action("PanelsForCanvas", "Frame")/" + canvasId,
            })
            .done(function (data) {
                var panels = $("select#PanelId"), v = panels.val();
                panels.children("[value!='']").each(function (i, p) {
                    $(p).remove();
                });
                $(data).each(function (i, p) {
                    panels.append('<option value="' + p.id + (p.id == v ? '" selected>' : '">') + p.name + '</option>');
                });
            });
        };
        $(document).ready(function () {
            $('select#CanvasId').change(function () {
                fillPanels();
            });
        });
    </script>
}